/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PzpRouteImport } from './routes/pzp'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as HavarijneRouteImport } from './routes/havarijne'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FinancovanieRouteImport } from './routes/financovanie'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PzpIndexRouteImport } from './routes/pzp.index'
import { Route as HavarijneIndexRouteImport } from './routes/havarijne.index'
import { Route as PzpInsurerRouteImport } from './routes/pzp.$insurer'
import { Route as HavarijneInsurerRouteImport } from './routes/havarijne.$insurer'
import { Route as FinancovanieProviderRouteImport } from './routes/financovanie.$provider'

const PzpRoute = PzpRouteImport.update({
  id: '/pzp',
  path: '/pzp',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const HavarijneRoute = HavarijneRouteImport.update({
  id: '/havarijne',
  path: '/havarijne',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancovanieRoute = FinancovanieRouteImport.update({
  id: '/financovanie',
  path: '/financovanie',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PzpIndexRoute = PzpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PzpRoute,
} as any)
const HavarijneIndexRoute = HavarijneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HavarijneRoute,
} as any)
const PzpInsurerRoute = PzpInsurerRouteImport.update({
  id: '/$insurer',
  path: '/$insurer',
  getParentRoute: () => PzpRoute,
} as any)
const HavarijneInsurerRoute = HavarijneInsurerRouteImport.update({
  id: '/$insurer',
  path: '/$insurer',
  getParentRoute: () => HavarijneRoute,
} as any)
const FinancovanieProviderRoute = FinancovanieProviderRouteImport.update({
  id: '/$provider',
  path: '/$provider',
  getParentRoute: () => FinancovanieRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/financovanie': typeof FinancovanieRouteWithChildren
  '/guide': typeof GuideRoute
  '/havarijne': typeof HavarijneRouteWithChildren
  '/my-account': typeof MyAccountRoute
  '/partners': typeof PartnersRoute
  '/pzp': typeof PzpRouteWithChildren
  '/financovanie/$provider': typeof FinancovanieProviderRoute
  '/havarijne/$insurer': typeof HavarijneInsurerRoute
  '/pzp/$insurer': typeof PzpInsurerRoute
  '/havarijne/': typeof HavarijneIndexRoute
  '/pzp/': typeof PzpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/financovanie': typeof FinancovanieRouteWithChildren
  '/guide': typeof GuideRoute
  '/my-account': typeof MyAccountRoute
  '/partners': typeof PartnersRoute
  '/financovanie/$provider': typeof FinancovanieProviderRoute
  '/havarijne/$insurer': typeof HavarijneInsurerRoute
  '/pzp/$insurer': typeof PzpInsurerRoute
  '/havarijne': typeof HavarijneIndexRoute
  '/pzp': typeof PzpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/financovanie': typeof FinancovanieRouteWithChildren
  '/guide': typeof GuideRoute
  '/havarijne': typeof HavarijneRouteWithChildren
  '/my-account': typeof MyAccountRoute
  '/partners': typeof PartnersRoute
  '/pzp': typeof PzpRouteWithChildren
  '/financovanie/$provider': typeof FinancovanieProviderRoute
  '/havarijne/$insurer': typeof HavarijneInsurerRoute
  '/pzp/$insurer': typeof PzpInsurerRoute
  '/havarijne/': typeof HavarijneIndexRoute
  '/pzp/': typeof PzpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/financovanie'
    | '/guide'
    | '/havarijne'
    | '/my-account'
    | '/partners'
    | '/pzp'
    | '/financovanie/$provider'
    | '/havarijne/$insurer'
    | '/pzp/$insurer'
    | '/havarijne/'
    | '/pzp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/financovanie'
    | '/guide'
    | '/my-account'
    | '/partners'
    | '/financovanie/$provider'
    | '/havarijne/$insurer'
    | '/pzp/$insurer'
    | '/havarijne'
    | '/pzp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/financovanie'
    | '/guide'
    | '/havarijne'
    | '/my-account'
    | '/partners'
    | '/pzp'
    | '/financovanie/$provider'
    | '/havarijne/$insurer'
    | '/pzp/$insurer'
    | '/havarijne/'
    | '/pzp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FinancovanieRoute: typeof FinancovanieRouteWithChildren
  GuideRoute: typeof GuideRoute
  HavarijneRoute: typeof HavarijneRouteWithChildren
  MyAccountRoute: typeof MyAccountRoute
  PartnersRoute: typeof PartnersRoute
  PzpRoute: typeof PzpRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pzp': {
      id: '/pzp'
      path: '/pzp'
      fullPath: '/pzp'
      preLoaderRoute: typeof PzpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/havarijne': {
      id: '/havarijne'
      path: '/havarijne'
      fullPath: '/havarijne'
      preLoaderRoute: typeof HavarijneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financovanie': {
      id: '/financovanie'
      path: '/financovanie'
      fullPath: '/financovanie'
      preLoaderRoute: typeof FinancovanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pzp/': {
      id: '/pzp/'
      path: '/'
      fullPath: '/pzp/'
      preLoaderRoute: typeof PzpIndexRouteImport
      parentRoute: typeof PzpRoute
    }
    '/havarijne/': {
      id: '/havarijne/'
      path: '/'
      fullPath: '/havarijne/'
      preLoaderRoute: typeof HavarijneIndexRouteImport
      parentRoute: typeof HavarijneRoute
    }
    '/pzp/$insurer': {
      id: '/pzp/$insurer'
      path: '/$insurer'
      fullPath: '/pzp/$insurer'
      preLoaderRoute: typeof PzpInsurerRouteImport
      parentRoute: typeof PzpRoute
    }
    '/havarijne/$insurer': {
      id: '/havarijne/$insurer'
      path: '/$insurer'
      fullPath: '/havarijne/$insurer'
      preLoaderRoute: typeof HavarijneInsurerRouteImport
      parentRoute: typeof HavarijneRoute
    }
    '/financovanie/$provider': {
      id: '/financovanie/$provider'
      path: '/$provider'
      fullPath: '/financovanie/$provider'
      preLoaderRoute: typeof FinancovanieProviderRouteImport
      parentRoute: typeof FinancovanieRoute
    }
  }
}

interface FinancovanieRouteChildren {
  FinancovanieProviderRoute: typeof FinancovanieProviderRoute
}

const FinancovanieRouteChildren: FinancovanieRouteChildren = {
  FinancovanieProviderRoute: FinancovanieProviderRoute,
}

const FinancovanieRouteWithChildren = FinancovanieRoute._addFileChildren(
  FinancovanieRouteChildren,
)

interface HavarijneRouteChildren {
  HavarijneInsurerRoute: typeof HavarijneInsurerRoute
  HavarijneIndexRoute: typeof HavarijneIndexRoute
}

const HavarijneRouteChildren: HavarijneRouteChildren = {
  HavarijneInsurerRoute: HavarijneInsurerRoute,
  HavarijneIndexRoute: HavarijneIndexRoute,
}

const HavarijneRouteWithChildren = HavarijneRoute._addFileChildren(
  HavarijneRouteChildren,
)

interface PzpRouteChildren {
  PzpInsurerRoute: typeof PzpInsurerRoute
  PzpIndexRoute: typeof PzpIndexRoute
}

const PzpRouteChildren: PzpRouteChildren = {
  PzpInsurerRoute: PzpInsurerRoute,
  PzpIndexRoute: PzpIndexRoute,
}

const PzpRouteWithChildren = PzpRoute._addFileChildren(PzpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FinancovanieRoute: FinancovanieRouteWithChildren,
  GuideRoute: GuideRoute,
  HavarijneRoute: HavarijneRouteWithChildren,
  MyAccountRoute: MyAccountRoute,
  PartnersRoute: PartnersRoute,
  PzpRoute: PzpRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
